env:
  browser: true
  es6: true
  node: true
extends:
  - standard
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  project: client/scripts/tsconfig.json
  ecmaVersion: 2019
  sourceType: module
rules:
  indent:
    - error
    - tab
  semi:
    - error
    - always
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-restricted-syntax:
    - error
    -
      selector: "BinaryExpression[operator='>']"
      message: "Expected < instead of >."
    -
      selector: "BinaryExpression[operator='>=']"
      message: "Expected <= instead of >=."
